name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2

      - name: Verificar mudanças pendentes
        run: |
          git status

      - name: Adicionar e commitar mudanças, se necessário
        run: |
          git add -A
          git commit -m "Salvando mudanças antes do pull" || echo "Nenhuma mudança para commit"

      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Configurar usuário do GitHub
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Realizar pull com rebase
        run: |
          git pull --rebase

      - name: Enviar mudanças para o repositório
        run: |
          git push
